//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KRIKOS360_INALPA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SBDABEJERMAN : DbContext
    {
        public SBDABEJERMAN()
            : base("name=SBDABEJERMAN")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<string> KrikosComprobantesAsoc(Nullable<int> comprobanteSDK_id)
        {
            var comprobanteSDK_idParameter = comprobanteSDK_id.HasValue ?
                new ObjectParameter("ComprobanteSDK_id", comprobanteSDK_id) :
                new ObjectParameter("ComprobanteSDK_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("KrikosComprobantesAsoc", comprobanteSDK_idParameter);
        }
    }
}
